# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================


spring:
    liquibase:
        change-log: classpath:db/liquibase-changelog.xml
    datasource:
        url: jdbc:mysql://localhost:3306/warehouse?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
        username: warehouse
        password: password
    application:
        name: WarehouseSrvApplication
